### GraphQL
POST http://localhost:8088/graphql
X-Request-Type: GraphQL

query {
    courses {
        id
        name
      	courseDetails {
          description
          syllabus
          enrolledEmployees {
          	id
            name
          }
        }
    }
}
