### Roles
GET http://localhost:8085/api/roles

### Employees
GET http://localhost:8085/api/employees

### Courses
GET http://localhost:8085/api/courses

### Courses
GET http://localhost:8085/api/courses/1

### Roles
GET http://localhost:8085/dummy/api/roles

### Employees
GET http://localhost:8085/dummy/api/employees

