apiVersion: v1
kind: ConfigMap
metadata:
  name: employees-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: employees
  POSTGRES_USER: employees
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employees-postgres-persistence-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.0 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: employees-postgres-config
            - secretRef:
                name: employees-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: employees-postgres-persistence-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Domain name
spec:
  type: ClusterIP
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
