apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employee-service
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - image: employee-service:0.0.1
        name: employee-service
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/employees
          - name: SERVER_PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-service
  name: employee-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employee-service
  type: ClusterIP
