server:
  port: 8085
spring:
  cloud:
    gateway:
      filter:
        local-response-cache:
          enabled: true
      routes:
        - id: roles
          uri: http://localhost:8081/
          predicates:
            - Path=/api/roles
        - id: employees
          uri: http://localhost:8081/
          predicates:
            - Path=/api/employees
          filters:
            - LocalResponseCache=30m,500MB
        - id: courses
          uri: http://localhost:8083/
          predicates:
            - Path=/api/courses